# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Relay_pb2 as Relay__pb2


class relayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deliver = channel.unary_unary(
                '/relay/Deliver',
                request_serializer=Relay__pb2.Msg_request.SerializeToString,
                response_deserializer=Relay__pb2.Msg_response.FromString,
                )
        self.Cast = channel.unary_unary(
                '/relay/Cast',
                request_serializer=Relay__pb2.branch_comm.SerializeToString,
                response_deserializer=Relay__pb2.branch_res.FromString,
                )


class relayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Deliver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_relayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deliver': grpc.unary_unary_rpc_method_handler(
                    servicer.Deliver,
                    request_deserializer=Relay__pb2.Msg_request.FromString,
                    response_serializer=Relay__pb2.Msg_response.SerializeToString,
            ),
            'Cast': grpc.unary_unary_rpc_method_handler(
                    servicer.Cast,
                    request_deserializer=Relay__pb2.branch_comm.FromString,
                    response_serializer=Relay__pb2.branch_res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class relay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deliver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay/Deliver',
            Relay__pb2.Msg_request.SerializeToString,
            Relay__pb2.Msg_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay/Cast',
            Relay__pb2.branch_comm.SerializeToString,
            Relay__pb2.branch_res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
