# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Relay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRelay.proto\"J\n\x0bMsg_request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\"Z\n\x0b\x62ranch_comm\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x12\x0e\n\x06\x62ranch\x18\x06 \x01(\x05\"Y\n\nbranch_res\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x12\x0e\n\x06\x62ranch\x18\x06 \x01(\x05\"[\n\x0cMsg_response\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x32V\n\x05relay\x12(\n\x07\x44\x65liver\x12\x0c.Msg_request\x1a\r.Msg_response\"\x00\x12#\n\x04\x43\x61st\x12\x0c.branch_comm\x1a\x0b.branch_res\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Relay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MSG_REQUEST']._serialized_start=15
  _globals['_MSG_REQUEST']._serialized_end=89
  _globals['_BRANCH_COMM']._serialized_start=91
  _globals['_BRANCH_COMM']._serialized_end=181
  _globals['_BRANCH_RES']._serialized_start=183
  _globals['_BRANCH_RES']._serialized_end=272
  _globals['_MSG_RESPONSE']._serialized_start=274
  _globals['_MSG_RESPONSE']._serialized_end=365
  _globals['_RELAY']._serialized_start=367
  _globals['_RELAY']._serialized_end=453
# @@protoc_insertion_point(module_scope)
